### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by andreicek** [cathaysia/tree-sitter-asciidoc#1]
Can you please provide a license for this project?

I just [created an extension](https://github.com/andreicek/zed-asciidoc) that uses your work in order to provide syntax highlighting in the Zed editor.

**Comment by cathaysia** [comment]
I add the MIT licenset. but I want to say that:

The project is a fork of https://github.com/tree-sitter-grammars/tree-sitter-markdown. It was originally intended to allow [aerial](https://github.com/stevearc/aerial.nvim) to support asciidoc outlining and code block highlighting. Therefore it has little ability to parse other than asciidoc formats. I wouldn't recommend this project for anything other than that, it was largely created to solve my problem. Asciidoc is very difficult to parse using lr1, and I don't have a lot of experience writing parsers

In addition, since there is no inline parser, it cannot parse any inline syntax (such as italics, bold, etc.)

**Comment by andreicek** [comment]
Thanks -- for this use case it actually works OK since there is no other way to get highlighting in.

Thanks for your answer and time.

**Comment by cathaysia** [comment]
I update some code for this parser, did you have interesting about it?

here is the currently state: #2
